[package]
name = "sherman"
version = "0.1.0"
authors = ["Em Sharnoff <git@sharnoff.io>"]
edition = "2024"
repository = "https://github.com/dymium-editor/sherman"
license = "MIT OR Apache-2.0"
description = "Run-length encoded, highly-parameterizable balanced binary search tree"

[dependencies]
arbitrary = { version = "1.4.1", optional = true, features = ["derive"] }
serde = { version = "1", optional = true }

[features]
default = ["fuzz"]
nightly = []
serde = ["dep:serde"]
fuzz = ["dep:arbitrary"]
