[package]
name = "sherman-fuzz-utils"
version = "0.0.0"
authors = ["sharnoff <github@max.sharnoff.org>"]
publish = false
edition = "2021"

[dependencies]
sherman = { path = "..", features = ["fuzz"] }
arbitrary = { version = "1.1.3", features = ["derive"] }
