[package]
name = "sherman-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
sherman = { path = "..", features = ["fuzz"] }

[[bin]]
name = "basic"
path = "fuzz_targets/basic.rs"
test = false
doc = false
bench = false

[[bin]]
name = "basic_range"
path = "fuzz_targets/basic_range.rs"
test = false
doc = false
bench = false

[[bin]]
name = "checked"
path = "fuzz_targets/checked.rs"
test = false
doc = false
bench = false

[[bin]]
name = "checked_range"
path = "fuzz_targets/checked_range.rs"
test = false
doc = false
bench = false

[[bin]]
name = "multi_cow"
path = "fuzz_targets/multi_cow.rs"
test = false
doc = false
bench = false

[[bin]]
name = "multi_cow_range"
path = "fuzz_targets/multi_cow_range.rs"
test = false
doc = false
bench = false

[[bin]]
name = "slice_ref"
path = "fuzz_targets/slice_ref.rs"
test = false
doc = false
bench = false

[[bin]]
name = "slice_ref_range"
path = "fuzz_targets/slice_ref_range.rs"
test = false
doc = false
bench = false
