use arbitrary::{Arbitrary, Unstructured};
use std::fmt::{self, Debug, Display};
use std::ops::Range;
use std::panic::{self, RefUnwindSafe, UnwindSafe};

use crate::fuzz::{Fake, FakeStableRef, IndexInfo, RustExpr, RustType, TrackedIndex, TrackedSlice};
use crate::param;
use crate::{Index, RleTree, Slice, StableRef};

/// An operation on an [`RleTree`] (or group of `RleTree`s) that may be generated by a fuzzer
///
/// Usage proceeds in two phases:
///
/// 1. The initial generation of a sequence of operations (via [`OpSequence`]), using a faked
///    implementation to determine the correct results; and
/// 2. Run the operations against real `RleTree`s and check the results against the ones expected
///    from the faked implementation
///
/// If there are any differences from the expected results, the `Debug` implementation of
/// `OpSequence` uses `write_init_stmt()` and `write_stmt()` to print a unit test to reproduce the
/// failure.
pub trait ArbitraryOp: Sized {
    /// State used during generation, as a "ground truth" implementation
    type FakeState;
    /// Context for validation, that the state may borrow from
    type Context;
    /// State used during validation
    type RealState<'c>;

    /// Produces the initial `FakeState`
    fn fake_state() -> Self::FakeState;
    /// Produces the initial context for validation
    fn context() -> Self::Context;
    /// Produces the initial `RealState`
    fn real_state<'c>(ctx: &'c Self::Context) -> Self::RealState<'c>;

    /// Generates the operation from
    fn generate(
        u: &mut Unstructured<'_>,
        state: Self::FakeState,
    ) -> arbitrary::Result<(Self, Option<Self::FakeState>)>;

    /// Executes the operation on the state, and assert that it is
    fn execute_assert<'c>(
        &self,
        ctx: &'c Self::Context,
        state: Self::RealState<'c>,
    ) -> Option<Self::RealState<'c>>;

    /// Writes the start of a unit test to reproduce the assertions from these `ArbitraryOp`s
    fn write_test_start(f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("#[test]\n")?;
        f.write_str("fn test_case() {\n")?;
        Ok(())
    }

    /// Writes the statements at the start of a unit test to reproduce the initial `RealState`
    fn write_init_stmts(f: &mut fmt::Formatter) -> fmt::Result;

    /// Writes the statements to execute the operation and check its results
    fn write_execute_stmts(&self, f: &mut fmt::Formatter) -> fmt::Result;

    fn write_test_end(f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("}\n")?;
        Ok(())
    }
}

/// A sequence of [`ArbitraryOp`]s
pub struct OpSequence<C> {
    ops: Vec<C>,
}

impl<'d, Op> Arbitrary<'d> for OpSequence<Op>
where
    Op: ArbitraryOp,
{
    fn arbitrary(u: &mut Unstructured<'d>) -> arbitrary::Result<Self> {
        let mut ops: Vec<Op> = Vec::new();

        let mut state = Some(Op::fake_state());

        while let Some(s) = state
            && !u.is_empty()
        {
            let (op, next_state) = Op::generate(u, s)?;
            ops.push(op);
            state = next_state;
        }

        Ok(OpSequence { ops })
    }
}

impl<Op: ArbitraryOp> OpSequence<Op> {
    /// Executes the sequence of operations, checking at each step that the result matches what's
    /// expected from the faked state
    pub fn execute_assert(&self) {
        let ctx = Op::context();
        let mut state = Op::real_state(&ctx);
        let mut ops = self.ops.iter().enumerate().peekable();
        while let Some((idx, op)) = ops.next() {
            let next_state = op.execute_assert(&ctx, state);
            match next_state {
                Some(s) => state = s,
                // Operation consumed state & didn't give it back.
                // Ok if this is the last op, otherwise unexpected.
                None => match ops.peek() {
                    None => return,
                    Some(_) => panic!(
                        "bad ArbitraryOp impl? op idx={idx} executed without returning state"
                    ),
                },
            }
        }
    }
}

impl<Op> Debug for OpSequence<Op>
where
    Op: ArbitraryOp,
{
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        Op::write_test_start(f)?;
        Op::write_init_stmts(f)?;
        for c in &self.ops {
            c.write_execute_stmts(f)?;
        }
        Op::write_test_end(f)?;
        Ok(())
    }
}

fn expect_might_panic<R, F: UnwindSafe + FnOnce() -> R>(f: F) -> Result<R, ()> {
    // set a custom hook that does nothing, so we don't print panic information every time the mock
    // implementation panics
    panic::set_hook(Box::new(|_| {}));

    let result = panic::catch_unwind(f).map_err(|_| ());

    // remove our custom hook
    let _ = panic::take_hook();

    result
}

#[derive(Clone)]
pub enum BasicOperation<I, S> {
    /// `tree.get(index)`
    Get {
        index: I,
        /// If the call to `get()` should panic, then `Err(())`; otherwise, the range and slice
        /// returned by `get()`.
        expected: Result<(Range<I>, S), ()>,
    },
    /// `tree.iter((start, end))`
    Iter {
        start: Bound<I>,
        end: Bound<I>,
        /// If the call to `iter()` should panic, then `Err(())`; otherwise, the sequence of
        /// operations on the iterator, and their expected results.
        access: Result<Vec<IterOperation<I, S>>, ()>,
    },
    /// `tree.into_iter()`
    IntoIter {
        /// The sequence of operations on the iterator, and their expected results.
        access: Vec<IterOperation<I, S>>,
    },
    /// `tree.insert(index, slice, size)`
    Insert {
        index: I,
        slice: S,
        size: I,
        /// Is this insertion expected to panic?
        panics: bool,
    },
    /// `tree.replace((start, end), slice, size)`
    ///
    /// We intentionally don't do anything with the returned values.
    Replace {
        start: Bound<I>,
        end: Bound<I>,
        slice: S,
        size: I,
        /// Is this replace expected to panic?
        panics: bool,
    },
    /// `_ = tree.remove((start, end))`
    ///
    /// While this does return a new `RleTree`, we intentionally don't do anything with it.
    /// We get decent coverage from `Drain` already, and it's better to keep the state simple here.
    Remove {
        start: Bound<I>,
        end: Bound<I>,
        /// Is this removal expected to panic?
        panics: bool,
    },
    /// `tree.drain((start, end))`
    Drain {
        start: Bound<I>,
        end: Bound<I>,
        /// If the call to `drain()` should panic, then `Err(())`; otherwise, the sequence of
        /// operations on the iterator, and their expected results.
        access: Result<Vec<IterOperation<I, S>>, ()>,
    },
    /// `tree.validate_balance()`
    Validate,
}

#[derive(Clone)]
pub struct IterOperation<I, S> {
    direction: IterDirection,
    value: Option<(Range<I>, S)>,
}

#[derive(Copy, Clone, Arbitrary)]
enum IterDirection {
    Front,
    Back,
}

#[derive(Copy, Clone)]
pub enum Bound<I> {
    Unbounded(I),
    Included(I),
    Excluded(I),
}

impl<I> Bound<I> {
    fn into_std(self) -> std::ops::Bound<I> {
        match self {
            Bound::Unbounded(_) => std::ops::Bound::Unbounded,
            Bound::Included(i) => std::ops::Bound::Included(i),
            Bound::Excluded(i) => std::ops::Bound::Excluded(i),
        }
    }

    fn map<F, R>(self, f: F) -> Bound<R>
    where
        F: FnOnce(I) -> R,
    {
        match self {
            Bound::Unbounded(i) => Bound::Unbounded(f(i)),
            Bound::Included(i) => Bound::Included(f(i)),
            Bound::Excluded(i) => Bound::Excluded(f(i)),
        }
    }

    fn value(self) -> I {
        match self {
            Bound::Unbounded(i) | Bound::Included(i) | Bound::Excluded(i) => i,
        }
    }
}

fn format_bounds<'b, I: RustExpr>(start: &'b Bound<I>, end: &'b Bound<I>) -> impl 'b + Display {
    struct R<'b, I>(&'b Bound<I>, &'b Bound<I>);
    impl<'b, I: RustExpr> Display for R<'b, I> {
        fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
            match (self.0, self.1) {
                (Bound::Unbounded(_), Bound::Unbounded(_)) => f.write_str(".."),
                (Bound::Unbounded(_), Bound::Excluded(e)) => {
                    f.write_fmt(format_args!("..{}", e.display_rust_expr()))
                }
                (Bound::Unbounded(_), Bound::Included(e)) => {
                    f.write_fmt(format_args!("..={}", e.display_rust_expr()))
                }
                (Bound::Excluded(_), _) => unreachable!(),
                (Bound::Included(s), Bound::Unbounded(_)) => {
                    f.write_fmt(format_args!("{}..", s.display_rust_expr()))
                }
                (Bound::Included(s), Bound::Excluded(e)) => f.write_fmt(format_args!(
                    "{}..{}",
                    s.display_rust_expr(),
                    e.display_rust_expr()
                )),
                (Bound::Included(s), Bound::Included(e)) => f.write_fmt(format_args!(
                    "{}..={}",
                    s.display_rust_expr(),
                    e.display_rust_expr()
                )),
            }
        }
    }

    R(start, end)
}

impl<I, S> ArbitraryOp for BasicOperation<I, S>
where
    I: for<'d> Arbitrary<'d> + UnwindSafe + RefUnwindSafe + RustType + RustExpr + Index,
    S: for<'d> Arbitrary<'d>
        + UnwindSafe
        + RefUnwindSafe
        + RustType
        + RustExpr
        + Slice<I>
        + Debug
        + Clone
        + PartialEq,
{
    type FakeState = Fake<I, S>;
    type Context = ();
    type RealState<'a> = RleTree<I, S>;

    fn fake_state() -> Self::FakeState {
        Fake::new_empty()
    }

    fn context() -> Self::Context {}

    fn real_state(_ctx: &()) -> Self::RealState<'_> {
        RleTree::new_empty()
    }

    fn generate(
        u: &mut Unstructured<'_>,
        fake: Fake<I, S>,
    ) -> arbitrary::Result<(Self, Option<Fake<I, S>>)> {
        match BasicOperation::generate(u, fake) {
            Err(e) => Err(e),
            Ok((this, next_state)) => Ok((this, next_state.map(|(f, _)| f))),
        }
    }

    fn execute_assert(&self, _ctx: &(), tree: Self::RealState<'_>) -> Option<Self::RealState<'_>> {
        BasicOperation::execute_assert(self, tree).map(|(tree, _removed)| tree)
    }

    fn write_init_stmts(f: &mut fmt::Formatter) -> fmt::Result {
        f.write_fmt(format_args!(
            "    let mut tree: RleTree<{I}, {S}> = RleTree::new_empty();\n",
            I = I::display_rust_type(),
            S = S::display_rust_type(),
        ))
    }

    fn write_execute_stmts(&self, f: &mut fmt::Formatter) -> fmt::Result {
        BasicOperation::write_execute_stmts(
            self,
            f,
            BasicOperationFormatFlags { tree: &"tree", remove_into: None },
        )
    }
}

struct BasicOperationFormatFlags<'d> {
    tree: &'d dyn fmt::Display,
    remove_into: Option<&'d dyn fmt::Display>,
}

impl<I, S> BasicOperation<I, S> {
    #[expect(clippy::type_complexity)]
    fn generate(
        u: &mut Unstructured<'_>,
        mut fake: Fake<I, S>,
    ) -> arbitrary::Result<(Self, Option<(Fake<I, S>, Option<Fake<I, S>>)>)>
    where
        I: for<'d> Arbitrary<'d> + UnwindSafe + RefUnwindSafe + Index,
        S: for<'d> Arbitrary<'d> + UnwindSafe + RefUnwindSafe + Slice<I> + Clone,
    {
        let count = std::mem::variant_count::<BasicOperation<I, S>>();
        match u.int_in_range(0..=count - 1)? {
            // BasicOperation::Get
            0 => {
                let index = I::arbitrary(u)?;
                let result = expect_might_panic(move || {
                    let (range, slice) = fake.get(index);
                    (range, S::clone(slice), fake)
                });
                let (expected, new_state) = match result {
                    Ok((range, slice, fake)) => (Ok((range, slice)), Some((fake, None))),
                    Err(_) => (Err(()), None),
                };

                Ok((BasicOperation::Get { index, expected }, new_state))
            }
            // BasicOperation::Iter
            1 => {
                let start = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded(I::ZERO),
                    1 => Bound::Included(I::arbitrary(u)?),
                    _ => unreachable!(),
                };
                let end = match u.int_in_range(0..=2)? {
                    0 => Bound::Unbounded(fake.size()),
                    1 => Bound::Included(I::arbitrary(u)?),
                    2 => Bound::Excluded(I::arbitrary(u)?),
                    _ => unreachable!(),
                };

                let access_directions = u.arbitrary::<Vec<IterDirection>>()?;
                let result = expect_might_panic(move || {
                    let mut iter = fake.iter((start.into_std(), end.into_std()));
                    let mut access = Vec::new();
                    for direction in access_directions {
                        let v = match direction {
                            IterDirection::Front => iter.next(),
                            IterDirection::Back => iter.next_back(),
                        };

                        access.push(IterOperation {
                            direction,
                            value: v.map(|(r, s)| (r, s.clone())),
                        });
                    }
                    (access, fake)
                });

                let (access, new_state) = match result {
                    Ok((vals, fake)) => (Ok(vals), Some((fake, None))),
                    Err(_) => (Err(()), None),
                };

                Ok((BasicOperation::Iter { start, end, access }, new_state))
            }
            // BasicOperation::IntoIter
            2 => {
                let access_directions = u.arbitrary::<Vec<IterDirection>>()?;
                let mut iter = fake.into_iter();
                let mut access = Vec::new();
                for direction in access_directions {
                    let value = match direction {
                        IterDirection::Front => iter.next(),
                        IterDirection::Back => iter.next_back(),
                    };

                    access.push(IterOperation { direction, value });
                }
                Ok((BasicOperation::IntoIter { access }, None))
            }
            // BasicOperation::Insert
            3 => {
                let index = I::arbitrary(u)?;
                let slice = S::arbitrary(u)?;
                let size = I::arbitrary(u)?;
                let slice_cloned = slice.clone();
                let result = expect_might_panic(move || {
                    fake.insert(index, slice_cloned, size);
                    fake
                });
                let (panics, new_state) = match result {
                    Ok(fake) => (false, Some((fake, None))),
                    Err(_) => (true, None),
                };

                Ok((BasicOperation::Insert { index, slice, size, panics }, new_state))
            }
            // BasicOperation::Replace
            4 => {
                let start = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded(I::ZERO),
                    1 => Bound::Included(I::arbitrary(u)?),
                    _ => unreachable!(),
                };
                let end = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded(fake.size()),
                    1 => Bound::Excluded(I::arbitrary(u)?),
                    _ => unreachable!(),
                };

                let slice = S::arbitrary(u)?;
                let size = I::arbitrary(u)?;

                let slice_cloned = slice.clone();
                let result = expect_might_panic(move || {
                    let removed =
                        fake.replace((start.into_std(), end.into_std()), slice_cloned, size);
                    (fake, removed)
                });

                let (panics, new_state) = match result {
                    Ok((fake, removed)) => (false, Some((fake, Some(removed)))),
                    Err(_) => (true, None),
                };

                Ok((BasicOperation::Replace { start, end, slice, size, panics }, new_state))
            }
            // BasicOperation::Remove
            5 => {
                let start = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded(I::ZERO),
                    1 => Bound::Included(I::arbitrary(u)?),
                    _ => unreachable!(),
                };
                let end = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded(fake.size()),
                    1 => Bound::Excluded(I::arbitrary(u)?),
                    _ => unreachable!(),
                };

                let result = expect_might_panic(move || {
                    let removed = fake.remove((start.into_std(), end.into_std()));
                    (fake, removed)
                });

                let (panics, new_state) = match result {
                    Ok((fake, removed)) => (false, Some((fake, Some(removed)))),
                    Err(_) => (true, None),
                };

                Ok((BasicOperation::Remove { start, end, panics }, new_state))
            }
            // BasicOperation::Drain
            6 => {
                let start = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded(I::ZERO),
                    1 => Bound::Included(I::arbitrary(u)?),
                    _ => unreachable!(),
                };
                let end = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded(fake.size()),
                    1 => Bound::Excluded(I::arbitrary(u)?),
                    _ => unreachable!(),
                };

                let access_directions = u.arbitrary::<Vec<IterDirection>>()?;
                let result = expect_might_panic(move || {
                    let mut drain = fake.drain((start.into_std(), end.into_std()));
                    let mut access = Vec::new();
                    for direction in access_directions {
                        let value = match direction {
                            IterDirection::Front => drain.next(),
                            IterDirection::Back => drain.next_back(),
                        };
                        access.push(IterOperation { direction, value });
                    }
                    drop(drain);
                    (access, fake)
                });

                let (access, new_state) = match result {
                    Ok((vals, fake)) => (Ok(vals), Some((fake, None))),
                    Err(_) => (Err(()), None),
                };

                Ok((BasicOperation::Drain { start, end, access }, new_state))
            }
            // BasicOperation::Validate
            7 => Ok((BasicOperation::Validate, Some((fake, None)))),
            v => unreachable!("bad BasicOperation variant {v}"),
        }
    }

    #[expect(clippy::type_complexity)]
    fn execute_assert<P>(
        &self,
        mut tree: RleTree<I, S, P>,
    ) -> Option<(RleTree<I, S, P>, Option<RleTree<I, S, P>>)>
    where
        I: UnwindSafe + RefUnwindSafe + Index,
        S: UnwindSafe + RefUnwindSafe + Slice<I> + Debug + PartialEq + Clone,
        P: param::RleTreeConfig<I, S> + param::SupportsUpdate<I, S>,
        <P as param::RleTreeConfig<I, S>>::Redirect: UnwindSafe + RefUnwindSafe,
    {
        match self {
            &BasicOperation::Get { index, ref expected } => match expected {
                Ok((range, slice)) => {
                    let entry = tree.get(index);
                    assert_eq!(entry.range(), *range);
                    assert_eq!(entry.slice(), slice);
                    drop(entry);
                    Some((tree, None))
                }
                Err(()) => {
                    assert!(expect_might_panic(|| tree.get(index)).is_err());
                    None
                }
            },
            &BasicOperation::Iter { start, end, ref access } => match access {
                Ok(seq) => {
                    let mut iter = tree.iter((start.into_std(), end.into_std()));
                    for op in seq {
                        let item = match op.direction {
                            IterDirection::Front => iter.next(),
                            IterDirection::Back => iter.next_back(),
                        };

                        let actual = item.map(|entry| (entry.range(), entry.slice().clone()));
                        assert_eq!(actual, op.value);
                    }
                    drop(iter);
                    Some((tree, None))
                }
                Err(()) => {
                    assert!(
                        expect_might_panic(|| tree.iter((start.into_std(), end.into_std())))
                            .is_err()
                    );
                    None
                }
            },
            BasicOperation::IntoIter { access } => {
                let mut iter = tree.into_iter();
                for op in access {
                    let item = match op.direction {
                        IterDirection::Front => iter.next(),
                        IterDirection::Back => iter.next_back(),
                    };

                    assert_eq!(item, op.value);
                }
                None
            }
            BasicOperation::Insert { index, slice, size, panics } => match panics {
                false => {
                    tree.insert(*index, slice.clone(), *size);
                    Some((tree, None))
                }
                true => {
                    let slice_clone = slice.clone();
                    assert!(
                        expect_might_panic(move || tree.insert(*index, slice_clone, *size))
                            .is_err()
                    );
                    None
                }
            },
            BasicOperation::Replace { start, end, slice, size, panics } => match panics {
                false => {
                    let removed =
                        tree.replace((start.into_std(), end.into_std()), slice.clone(), *size);
                    Some((tree, Some(removed.into_tree())))
                }
                true => {
                    let slice_clone = slice.clone();
                    assert!(
                        expect_might_panic(move || tree.replace(
                            (start.into_std(), end.into_std()),
                            slice_clone,
                            *size
                        ))
                        .is_err()
                    );
                    None
                }
            },
            BasicOperation::Remove { start, end, panics } => match panics {
                false => {
                    let removed = tree.remove((start.into_std(), end.into_std()));
                    Some((tree, Some(removed.into_tree())))
                }
                true => {
                    assert!(
                        expect_might_panic(move || tree.remove((start.into_std(), end.into_std())))
                            .is_err()
                    );
                    None
                }
            },
            BasicOperation::Drain { start, end, access } => match access {
                Ok(seq) => {
                    let mut drain = tree.drain((start.into_std(), end.into_std()));
                    for op in seq {
                        let item = match op.direction {
                            IterDirection::Front => drain.next(),
                            IterDirection::Back => drain.next_back(),
                        };

                        assert_eq!(item, op.value);
                    }
                    drop(drain);
                    Some((tree, None))
                }
                Err(()) => {
                    assert!(
                        expect_might_panic(move || {
                            _ = tree.drain((start.into_std(), end.into_std()));
                        })
                        .is_err()
                    );
                    None
                }
            },
            BasicOperation::Validate => {
                tree.validate_balance();
                Some((tree, None))
            }
        }
    }

    fn write_execute_stmts(
        &self,
        f: &mut fmt::Formatter,
        flags: BasicOperationFormatFlags<'_>,
    ) -> fmt::Result
    where
        I: RustExpr,
        S: RustExpr,
    {
        let BasicOperationFormatFlags { tree, remove_into } = flags;

        match self {
            BasicOperation::Get { index, expected } => match expected {
                Ok((range, slice)) => {
                    f.write_str("    {\n")?;
                    f.write_fmt(format_args!(
                        "        let entry = {tree}.get({index});\n",
                        index = index.display_rust_expr()
                    ))?;
                    f.write_fmt(format_args!(
                        "        assert_eq!(entry.range(), {range});\n",
                        range = range.display_rust_expr()
                    ))?;
                    f.write_fmt(format_args!(
                        "        assert_eq!(entry.slice(), &{slice});\n",
                        slice = slice.display_rust_expr()
                    ))?;
                    f.write_str("    }\n")?;
                    Ok(())
                }
                Err(()) => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(|| {tree}.get({index})).is_err());\n",
                    index = index.display_rust_expr(),
                )),
            },
            BasicOperation::Iter { start, end, access } => match access {
                Ok(seq) if seq.is_empty() => f.write_fmt(format_args!(
                    "    let _ = {tree}.iter({range});\n",
                    range = format_bounds(start, end),
                )),
                Ok(seq) => {
                    // Sample output:
                    //
                    //   {
                    //       let mut iter = tree.iter({range});
                    //       {
                    //           let item = iter.{method}().unwrap();
                    //           assert_eq!(item.range(), {expected_range});
                    //           assert_eq!(item.slice(), {expected_slice});
                    //       }
                    //       assert!(iter.{method}().is_none());
                    //   }
                    f.write_str("    {\n")?;
                    f.write_fmt(format_args!(
                        "        let mut iter = {tree}.iter({range});\n",
                        range = format_bounds(start, end),
                    ))?;
                    for op in seq {
                        let method = match op.direction {
                            IterDirection::Front => "next",
                            IterDirection::Back => "next_back",
                        };

                        match &op.value {
                            None => f.write_fmt(format_args!("        assert!(iter.{method}().is_none());\n"))?,
                            Some((range, slice)) => {
                                f.write_str("        {\n")?;
                                f.write_fmt(format_args!("            let item = iter.{method}().unwrap();\n"))?;
                                f.write_fmt(format_args!("            assert_eq!(item.range(), {});\n", range.display_rust_expr()))?;
                                f.write_fmt(format_args!("            assert_eq!(item.slice(), &{});\n", slice.display_rust_expr()))?;
                                f.write_str("        }\n")?;
                            },
                        }
                    }
                    f.write_str("    }\n")
                },
                Err(()) => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(|| {tree}.iter({range})).is_err());\n",
                    range = format_bounds(start, end),
                )),
            },
            BasicOperation::IntoIter { access } => {
                if access.is_empty() {
                    f.write_fmt(format_args!("    let _ = {tree}.into_iter();\n"))
                } else {
                    // Sample output:
                    //
                    //   {
                    //       let mut iter = tree.into_iter();
                    //       assert_eq!(iter.{method}(), Some(({expected_range}, {expected_slice})));
                    //       assert_eq!(iter.{method}(), None);
                    //   }
                    f.write_str("    {\n")?;
                    f.write_fmt(format_args!("        let mut iter = {tree}.into_iter();\n"))?;
                    for op in access {
                        let method = match op.direction {
                            IterDirection::Front => "next",
                            IterDirection::Back => "next_back",
                        };

                        f.write_fmt(format_args!(
                            "        assert_eq!(iter.{method}(), {expected});\n",
                            expected = op.value.display_rust_expr(),
                        ))?;
                    }
                    f.write_str("    }\n")
                }
            }
            BasicOperation::Insert { index, slice, size, panics } => match panics {
                false => f.write_fmt(format_args!(
                    "    {tree}.insert({index}, {slice}, {size});\n",
                    index = index.display_rust_expr(),
                    slice = slice.display_rust_expr(),
                    size = size.display_rust_expr(),
                )),
                true => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(move || {tree}.insert({index}, {slice}, {size})).is_err());\n",
                    index = index.display_rust_expr(),
                    slice = slice.display_rust_expr(),
                    size = size.display_rust_expr(),
                )),
            },
            BasicOperation::Replace { start, end, slice, size, panics } => match panics {
                false => f.write_fmt(format_args!(
                    "    {lhs} = {tree}.replace({range}, {slice}, {size}).into_tree();\n",
                    lhs = remove_into.unwrap_or(&"_"),
                    range = format_bounds(start, end),
                    slice = slice.display_rust_expr(),
                    size = size.display_rust_expr(),
                )),
                true => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(move || {tree}.replace({range}, {slice}, {size})).is_err());\n",
                    range = format_bounds(start, end),
                    slice = slice.display_rust_expr(),
                    size = size.display_rust_expr(),
                )),
            },
            BasicOperation::Remove { start, end, panics } => match panics {
                false => f.write_fmt(format_args!(
                    "    {lhs} = {tree}.remove({range}).into_tree();\n",
                    lhs = remove_into.unwrap_or(&"_"),
                    range = format_bounds(start, end),
                )),
                true => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(move || {tree}.remove({range})).is_err());\n",
                    range = format_bounds(start, end),
                )),
            },
            BasicOperation::Drain { start, end, access } => match access {
                Ok(seq) if seq.is_empty() => f.write_fmt(format_args!(
                    "    let _ = {tree}.drain({range});\n",
                    range = format_bounds(start, end),
                )),
                Ok(seq) => {
                    // Sample output:
                    //
                    //   {
                    //       let mut drain = tree.drain({range});
                    //       assert_eq!(drain.{method}(), Some(({expected_range}, {expected_slice})));
                    //       assert_eq!(drain.{method}(), None);
                    //   }
                    f.write_str("    {\n")?;
                    f.write_fmt(format_args!(
                        "        let mut drain = {tree}.drain({range});\n",
                        range = format_bounds(start, end),
                    ))?;
                    for op in seq {
                        let method = match op.direction {
                            IterDirection::Front => "next",
                            IterDirection::Back => "next_back",
                        };

                        f.write_fmt(format_args!(
                            "        assert_eq!(drain.{method}(), {expected});\n",
                            expected = op.value.display_rust_expr(),
                        ))?;
                    }
                    f.write_str("    }\n")
                },
                Err(()) => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(move || drop({tree}.drain({range}))).is_err());\n",
                    range = format_bounds(start, end),
                )),
            },
            BasicOperation::Validate => f.write_fmt(format_args!(
                "    {tree}.validate_balance();\n",
            )),
        }
    }
}

/// Like [`BasicOperation`], but checks that [`RleTree`] respects index usage invariants
pub struct CheckedIndexOperation<I, S>(BasicOperation<I, S>);

impl<I, S> ArbitraryOp for CheckedIndexOperation<I, S>
where
    I: 'static + for<'d> Arbitrary<'d> + UnwindSafe + RefUnwindSafe + RustType + RustExpr + Index,
    S: 'static
        + for<'d> Arbitrary<'d>
        + UnwindSafe
        + RefUnwindSafe
        + RustType
        + RustExpr
        + Slice<I>
        + Debug
        + Clone
        + PartialEq,
{
    type FakeState = Fake<I, S>;
    type Context = IndexInfo<I>;
    type RealState<'c> = RleTree<TrackedIndex<'c, I>, TrackedSlice<S>>;

    fn fake_state() -> Self::FakeState {
        Fake::new_empty()
    }

    fn context() -> Self::Context {
        IndexInfo::new()
    }

    fn real_state<'c>(_ctx: &'c IndexInfo<I>) -> RleTree<TrackedIndex<'c, I>, TrackedSlice<S>> {
        RleTree::new_empty()
    }

    fn generate(
        u: &mut Unstructured<'_>,
        fake: Fake<I, S>,
    ) -> arbitrary::Result<(Self, Option<Fake<I, S>>)> {
        match BasicOperation::generate(u, fake) {
            Err(e) => Err(e),
            Ok((this, next_state)) => Ok((CheckedIndexOperation(this), next_state.map(|(f, _)| f))),
        }
    }

    fn execute_assert<'c>(
        &self,
        info: &'c IndexInfo<I>,
        tree: RleTree<TrackedIndex<'c, I>, TrackedSlice<S>>,
    ) -> Option<RleTree<TrackedIndex<'c, I>, TrackedSlice<S>>> {
        // Convert from: BasicOperation<I, S> to BasicOperation<TrackedIndex<I>, TrackedSlice<S>>,
        // matching the RleTree.
        let map_bound = |bound: Bound<I>| bound.map(|idx| info.i(idx));
        let map_range = |range: Range<_>| info.i(range.start)..info.i(range.end);
        let map_iter_seq = |seq: Vec<IterOperation<_, _>>| {
            seq.into_iter()
                .map(|op| IterOperation {
                    direction: op.direction,
                    value: op.value.map(|(r, s)| (map_range(r), TrackedSlice(s))),
                })
                .collect::<Vec<_>>()
        };

        let tracked = match self.0.clone() {
            BasicOperation::Get { index, expected } => BasicOperation::Get {
                index: info.i(index),
                expected: expected.map(|(r, s)| (map_range(r), TrackedSlice(s))),
            },
            BasicOperation::Iter { start, end, access } => BasicOperation::Iter {
                start: map_bound(start),
                end: map_bound(end),
                access: access.map(map_iter_seq),
            },
            BasicOperation::IntoIter { access } => {
                BasicOperation::IntoIter { access: map_iter_seq(access) }
            }
            BasicOperation::Insert { index, slice, size, panics } => {
                let (index, size) = info.prepare_insert(index, size);
                BasicOperation::Insert { index, slice: TrackedSlice(slice), size, panics }
            }
            BasicOperation::Replace { start, end, slice, size, panics } => {
                let start = map_bound(start);
                let end = map_bound(end);
                let (_, size) =
                    info.prepare_replace(start.value().value()..end.value().value(), size);
                let slice = TrackedSlice(slice);
                BasicOperation::Replace { start, end, slice, size, panics }
            }
            BasicOperation::Remove { start, end, panics } => {
                let range_start = start.value();
                let range_end = end.value();
                let start = map_bound(start);
                let end = map_bound(end);
                info.prepare_remove(range_start, range_end);
                BasicOperation::Remove { start, end, panics }
            }
            BasicOperation::Drain { start, end, access } => {
                let range_start = start.value();
                let range_end = end.value();
                let start = map_bound(start);
                let end = map_bound(end);
                let access = access.map(map_iter_seq);
                info.prepare_remove(range_start, range_end);
                BasicOperation::Drain { start, end, access }
            }
            BasicOperation::Validate => BasicOperation::Validate,
        };

        BasicOperation::execute_assert(&tracked, tree).map(|(tree, _removed)| tree)
    }

    fn write_init_stmts(f: &mut fmt::Formatter) -> fmt::Result {
        f.write_fmt(format_args!(
            "    let t: IndexInfo<{I}> = IndexInfo::new();\n",
            I = I::display_rust_type(),
        ))?;
        f.write_fmt(format_args!(
            "    let mut tree: RleTree<TrackedIndex<{I}>, TrackedSlice<{S}>> = RleTree::new_empty();\n",
            I = I::display_rust_type(),
            S = S::display_rust_type(),
        ))
    }

    fn write_execute_stmts(&self, f: &mut fmt::Formatter) -> fmt::Result {
        // Convert from: BasicOperation<I, S> to BasicOperation<CheckedIndex<I>, CheckedSlice<S>>,
        // which is slightly different from the RleTree, so that we can name external variables for
        // things like insertions & removals.
        let map_range =
            |range: Range<_>| CheckedIndex::Current(range.start)..CheckedIndex::Current(range.end);
        let map_bound = |bound: Bound<I>| bound.map(CheckedIndex::Current);
        let map_iter_seq = |seq: Vec<IterOperation<_, _>>| {
            seq.into_iter()
                .map(|op| IterOperation {
                    direction: op.direction,
                    value: op.value.map(|(r, s)| (map_range(r), CheckedSlice(s))),
                })
                .collect::<Vec<_>>()
        };

        let checked = match self.0.clone() {
            BasicOperation::Get { index, expected } => BasicOperation::Get {
                index: CheckedIndex::Current(index),
                expected: expected.map(|(r, s)| (map_range(r), CheckedSlice(s))),
            },
            BasicOperation::Iter { start, end, access } => BasicOperation::Iter {
                start: map_bound(start),
                end: map_bound(end),
                access: access.map(map_iter_seq),
            },
            BasicOperation::IntoIter { access } => {
                BasicOperation::IntoIter { access: map_iter_seq(access) }
            }
            BasicOperation::Insert { index, slice, size, panics } => {
                f.write_fmt(format_args!(
                    "    let (idx, size) = t.prepare_insert({index}, {size});\n",
                    index = index.display_rust_expr(),
                    size = size.display_rust_expr(),
                ))?;

                BasicOperation::Insert {
                    index: CheckedIndex::Named("idx"),
                    slice: CheckedSlice(slice),
                    size: CheckedIndex::Named("size"),
                    panics,
                }
            }
            BasicOperation::Replace { start, end, slice, size, panics } => {
                f.write_fmt(format_args!(
                    "    let (range, size) = t.prepare_replace({start}..{end}, {size});\n",
                    start = start.value().display_rust_expr(),
                    end = end.value().display_rust_expr(),
                    size = size.display_rust_expr(),
                ))?;

                BasicOperation::Replace {
                    start: start.map(|_| CheckedIndex::Named("range.start")),
                    end: end.map(|_| CheckedIndex::Named("range.end")),
                    slice: CheckedSlice(slice),
                    size: CheckedIndex::Named("size"),
                    panics,
                }
            }
            BasicOperation::Remove { start, end, panics } => {
                let (start, start_var, start_idx) = match start {
                    Bound::Unbounded(idx) => (Bound::Unbounded(CheckedIndex::Named("_")), "_", idx),
                    Bound::Included(idx) => {
                        (Bound::Included(CheckedIndex::Named("start")), "start", idx)
                    }
                    Bound::Excluded(idx) => {
                        (Bound::Excluded(CheckedIndex::Named("start")), "start", idx)
                    }
                };
                let (end, end_var, end_idx) = match end {
                    Bound::Unbounded(idx) => (Bound::Unbounded(CheckedIndex::Named("_")), "_", idx),
                    Bound::Included(idx) => {
                        (Bound::Included(CheckedIndex::Named("end")), "end", idx)
                    }
                    Bound::Excluded(idx) => {
                        (Bound::Excluded(CheckedIndex::Named("end")), "end", idx)
                    }
                };

                f.write_fmt(format_args!(
                    "    let ({start_var}, {end_var}) = t.prepare_remove({start_idx}, {end_idx});\n",
                    start_idx = start_idx.display_rust_expr(),
                    end_idx = end_idx.display_rust_expr(),
                ))?;
                BasicOperation::Remove { start, end, panics }
            }
            BasicOperation::Drain { start, end, access } => {
                let (start, start_var, start_idx) = match start {
                    Bound::Unbounded(idx) => (Bound::Unbounded(CheckedIndex::Named("_")), "_", idx),
                    Bound::Included(idx) => {
                        (Bound::Included(CheckedIndex::Named("start")), "start", idx)
                    }
                    Bound::Excluded(idx) => {
                        (Bound::Excluded(CheckedIndex::Named("start")), "start", idx)
                    }
                };
                let (end, end_var, end_idx) = match end {
                    Bound::Unbounded(idx) => (Bound::Unbounded(CheckedIndex::Named("_")), "_", idx),
                    Bound::Included(idx) => {
                        (Bound::Included(CheckedIndex::Named("end")), "end", idx)
                    }
                    Bound::Excluded(idx) => {
                        (Bound::Excluded(CheckedIndex::Named("end")), "end", idx)
                    }
                };

                f.write_fmt(format_args!(
                    "    let ({start_var}, {end_var}) = t.prepare_remove({start_idx}, {end_idx});\n",
                    start_idx = start_idx.display_rust_expr(),
                    end_idx = end_idx.display_rust_expr(),
                ))?;

                let access = access.map(|seq| {
                    seq.into_iter()
                        .map(|op| IterOperation {
                            direction: op.direction,
                            value: op.value.map(|(r, s)| {
                                let r =
                                    CheckedIndex::Previous(r.start)..CheckedIndex::Previous(r.end);
                                let s = CheckedSlice(s);
                                (r, s)
                            }),
                        })
                        .collect::<Vec<_>>()
                });

                BasicOperation::Drain { start, end, access }
            }
            BasicOperation::Validate => BasicOperation::Validate,
        };

        BasicOperation::write_execute_stmts(
            &checked,
            f,
            BasicOperationFormatFlags { tree: &"tree", remove_into: None },
        )
    }
}

enum CheckedIndex<I> {
    Named(&'static str),
    Current(I),
    Previous(I),
}

impl<I: RustExpr> RustExpr for CheckedIndex<I> {
    fn write_rust_expr(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            CheckedIndex::Named(var) => f.write_str(var),
            CheckedIndex::Current(idx) => {
                f.write_fmt(format_args!("t.i({})", idx.display_rust_expr()))
            }
            CheckedIndex::Previous(idx) => {
                f.write_fmt(format_args!("t.p({})", idx.display_rust_expr()))
            }
        }
    }
}

struct CheckedSlice<S>(S);

impl<S: RustExpr> RustExpr for CheckedSlice<S> {
    fn write_rust_expr(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_fmt(format_args!("TrackedSlice({})", self.0.display_rust_expr()))
    }
}

pub enum MultiCowOperation<I, S> {
    /// A `BasicOperation` on an existing tree
    ///
    /// Those operations behave the same, with the exception that `BasicOperation::Remove` and
    /// `BasicOperation::Replace` also create new trees (in which case the new `TreeId` will be the
    /// final parameter).
    Basic(TreeId, BasicOperation<I, S>, Option<TreeId>),

    /// `let {0} = RleTree::new_empty()`
    NewEmpty(TreeId),

    /// `let {1} = {0}.shallow_clone()`
    ShallowClone(TreeId, TreeId),

    /// `{new_id} = {dst}.replace_many((start, end), {src}).into_tree()`
    ReplaceMany {
        dst: TreeId,
        src: TreeId,
        start: Bound<I>,
        end: Bound<I>,
        new_id: Result<TreeId, ()>,
    },
}

impl<I, S> ArbitraryOp for MultiCowOperation<I, S>
where
    I: for<'d> Arbitrary<'d> + UnwindSafe + RefUnwindSafe + RustType + RustExpr + Index,
    S: for<'d> Arbitrary<'d>
        + UnwindSafe
        + RefUnwindSafe
        + RustType
        + RustExpr
        + Slice<I>
        + Debug
        + Clone
        + PartialEq,
{
    type FakeState = FakeCowGroup<I, S>;
    type Context = ();
    type RealState<'a> = CowGroup<I, S>;

    fn fake_state() -> Self::FakeState {
        FakeCowGroup::new()
    }

    fn context() -> Self::Context {}

    fn real_state(_ctx: &()) -> Self::RealState<'_> {
        CowGroup::new()
    }

    fn generate(
        u: &mut Unstructured<'_>,
        mut group: Self::FakeState,
    ) -> arbitrary::Result<(Self, Option<Self::FakeState>)> {
        let (base_id, snd_id) = group.generate_id_pair(u)?;

        let basic_count = std::mem::variant_count::<BasicOperation<I, S>>();
        let cow_single_count = 2;
        let cow_dual_count = 1;
        assert_eq!(
            cow_single_count + cow_dual_count,
            std::mem::variant_count::<MultiCowOperation<I, S>>() - 1
        );

        let total_count = match snd_id {
            Some(_) => basic_count + cow_single_count + cow_dual_count,
            None => basic_count + cow_single_count,
        };

        match u.int_in_range(0..=total_count - 1)? {
            // MultiCowOperation::NewEmpty
            0 => {
                let new_fake = Fake::new_empty();
                let new_id = group.add(new_fake);
                let op = MultiCowOperation::NewEmpty(new_id);
                Ok((op, Some(group)))
            }
            // MultiCowOperation::ShallowClone
            1 => {
                let new_fake = group.get(base_id).clone();
                let new_id = group.add(new_fake);
                let op = MultiCowOperation::ShallowClone(base_id, new_id);
                Ok((op, Some(group)))
            }
            // MultiCowOperation::ReplaceMany
            2 if let Some(src_id) = snd_id => {
                let (group, src_fake) = group.take(src_id);
                let group = group.discard().unwrap();
                let (group, mut dst_fake) = group.take(base_id);

                let start = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded(I::ZERO),
                    1 => Bound::Included(I::arbitrary(u)?),
                    _ => unreachable!(),
                };
                let end = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded(dst_fake.size()),
                    1 => Bound::Excluded(I::arbitrary(u)?),
                    _ => unreachable!(),
                };

                let result = expect_might_panic(move || {
                    let removed =
                        dst_fake.replace_many((start.into_std(), end.into_std()), src_fake);
                    (dst_fake, removed)
                });

                let (new_id, new_state) = match result {
                    Ok((fake, removed)) => {
                        let mut group = group.done(fake);
                        let new_id = group.add(removed);
                        (Ok(new_id), Some(group))
                    }
                    Err(_) => (Err(()), None),
                };

                Ok((
                    MultiCowOperation::ReplaceMany {
                        dst: base_id,
                        src: src_id,
                        start,
                        end,
                        new_id,
                    },
                    new_state,
                ))
            }
            // MultiCowOperation::Basic(_) ...
            c if c >= total_count - basic_count => {
                let (group, fake) = group.take(base_id);
                let (basic, fake) = BasicOperation::generate(u, fake)?;
                let (group, dst_id) = match fake {
                    None => (group.discard(), None),
                    Some((f, removed)) => {
                        let mut group = group.done(f);
                        let dst_id = removed.map(|f| group.add(f));
                        (Some(group), dst_id)
                    }
                };
                Ok((MultiCowOperation::Basic(base_id, basic, dst_id), group))
            }
            v => unreachable!("bad MultiCowOperation variant {v}"),
        }
    }

    fn execute_assert(&self, _ctx: &(), mut group: CowGroup<I, S>) -> Option<Self::RealState<'_>> {
        match self {
            MultiCowOperation::Basic(src_id, op, dst_id) => {
                let (g, tree) = group.take(*src_id);
                match op.execute_assert(tree) {
                    None => g.discard(),
                    Some((tree, removed)) => {
                        let mut group = g.done(tree);
                        if let Some(tree) = removed {
                            let id = group.add(tree);
                            assert_eq!(&Some(id), dst_id);
                        } else {
                            assert!(dst_id.is_none());
                        }
                        Some(group)
                    }
                }
            }
            &MultiCowOperation::NewEmpty(dst_id) => {
                let t = RleTree::new_empty();
                assert_eq!(dst_id, group.add(t));
                Some(group)
            }
            &MultiCowOperation::ShallowClone(src_id, dst_id) => {
                let src = group.get(src_id);
                let dst = src.shallow_clone();
                assert_eq!(dst_id, group.add(dst));
                Some(group)
            }
            &MultiCowOperation::ReplaceMany { dst, src, start, end, new_id } => match new_id {
                Ok(new_id) => {
                    let (g, src_tree) = group.take(src);
                    let group = g.discard().unwrap();
                    let (g, mut dst_tree) = group.take(dst);

                    let removed =
                        dst_tree.replace_many((start.into_std(), end.into_std()), src_tree);

                    let mut group = g.done(dst_tree);
                    let id = group.add(removed.into_tree());
                    assert_eq!(id, new_id);

                    Some(group)
                }
                Err(()) => {
                    let (g, src_tree) = group.take(src);
                    let group = g.discard().unwrap();
                    let (g, mut dst_tree) = group.take(dst);

                    assert!(
                        expect_might_panic(move || dst_tree
                            .replace_many((start.into_std(), end.into_std()), src_tree,))
                        .is_err()
                    );

                    g.discard()
                }
            },
        }
    }

    fn write_init_stmts(f: &mut fmt::Formatter) -> fmt::Result {
        let op = Self::NewEmpty(TreeId(0));
        op.write_execute_stmts(f)
    }

    fn write_execute_stmts(&self, f: &mut fmt::Formatter) -> fmt::Result {
        struct L(TreeId);
        impl Display for L {
            fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
                f.write_fmt(format_args!("let mut {}", self.0))
            }
        }

        match self {
            MultiCowOperation::Basic(src_id, op, dst_id) => {
                let remove_into = dst_id.map(L);
                op.write_execute_stmts(
                    f,
                    BasicOperationFormatFlags {
                        tree: src_id,
                        remove_into: remove_into.as_ref().map(|l| l as _),
                    },
                )
            }
            MultiCowOperation::NewEmpty(dst_id) => {
                f.write_fmt(format_args!(
                    "    let mut {dst_id}: RleTree<{I}, {S}, EnableCow> = RleTree::new_empty();\n",
                    I = I::display_rust_type(),
                    S = S::display_rust_type(),
                ))
            },
            MultiCowOperation::ShallowClone(src_id, dst_id) => {
                f.write_fmt(format_args!("    let mut {dst_id} = {src_id}.shallow_clone();\n"))
            }
            MultiCowOperation::ReplaceMany { dst, src, start, end, new_id } => match new_id {
                Ok(new_id) => f.write_fmt(format_args!(
                    "    let mut {new_id} = {dst}.replace_many({range}, {src});\n",
                    range = format_bounds(start, end),
                )),
                Err(()) => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(move || {dst}.replace_many({range}, {src})).is_err());\n",
                    range = format_bounds(start, end),
                )),
            },
        }
    }
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct TreeId(usize);

impl Display for TreeId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_fmt(format_args!("tree_{id}", id = self.0))
    }
}

pub struct FakeCowGroup<I, S> {
    fakes: Vec<Option<Fake<I, S>>>,
    count: usize,
}

struct FakeCowGroupWithRemoved<I, S> {
    group: FakeCowGroup<I, S>,
    removed: TreeId,
}

impl<I, S> FakeCowGroup<I, S>
where
    I: Index,
    S: Slice<I>,
{
    fn new() -> Self {
        FakeCowGroup { fakes: vec![Some(Fake::new_empty())], count: 1 }
    }

    fn generate_id_pair(
        &self,
        u: &mut Unstructured<'_>,
    ) -> arbitrary::Result<(TreeId, Option<TreeId>)> {
        let mut fst_idx = u.choose_index(self.count)?;
        let fst_id = 'fst: {
            for (i, f) in self.fakes.iter().enumerate() {
                if f.is_none() {
                    fst_idx += 1;
                }
                if fst_idx == i {
                    assert!(f.is_some());
                    break 'fst TreeId(fst_idx);
                }
            }

            panic!("unexpectedly failed to generate TreeId")
        };

        // If there's only one value, return that:
        if self.count <= 1 {
            return Ok((fst_id, None));
        }

        // Otherwise, generate a second:
        let mut snd_idx = u.choose_index(self.count - 1)?;
        let snd_id = 'snd: {
            for (i, f) in self.fakes.iter().enumerate() {
                if f.is_none() || i == fst_id.0 {
                    snd_idx += 1;
                }
                if snd_idx == i {
                    assert!(f.is_some());
                    break 'snd TreeId(snd_idx);
                }
            }

            panic!("unexpectedly failed to generate TreeId")
        };

        Ok((fst_id, Some(snd_id)))
    }

    fn get(&self, id: TreeId) -> &Fake<I, S> {
        self.fakes[id.0].as_ref().unwrap()
    }

    fn add(&mut self, fake: Fake<I, S>) -> TreeId {
        let next_id = TreeId(self.fakes.len());
        self.fakes.push(Some(fake));
        self.count += 1;
        next_id
    }

    fn take(mut self, id: TreeId) -> (FakeCowGroupWithRemoved<I, S>, Fake<I, S>) {
        let fake = self.fakes[id.0].take().unwrap();
        let with_removed = FakeCowGroupWithRemoved { group: self, removed: id };
        (with_removed, fake)
    }
}

impl<I, S> FakeCowGroupWithRemoved<I, S> {
    fn done(self, fake: Fake<I, S>) -> FakeCowGroup<I, S> {
        let mut group = self.group;
        let idx = self.removed.0;
        assert!(group.fakes[idx].is_none());
        group.fakes[idx] = Some(fake);
        group
    }

    fn discard(mut self) -> Option<FakeCowGroup<I, S>> {
        match self.group.count {
            1 => None,
            _ => {
                self.group.count -= 1;
                Some(self.group)
            }
        }
    }
}

pub struct CowGroup<I, S> {
    trees: Vec<Option<RleTree<I, S, param::EnableCow>>>,
    count: usize,
}

struct CowGroupWithRemoved<I, S> {
    group: CowGroup<I, S>,
    removed: TreeId,
}

impl<I, S> CowGroup<I, S>
where
    I: Index,
    S: Slice<I>,
{
    fn new() -> Self {
        CowGroup { trees: vec![Some(RleTree::new_empty())], count: 1 }
    }

    fn get(&self, id: TreeId) -> &RleTree<I, S, param::EnableCow> {
        self.trees[id.0].as_ref().unwrap()
    }

    fn add(&mut self, tree: RleTree<I, S, param::EnableCow>) -> TreeId {
        let next_id = TreeId(self.trees.len());
        self.trees.push(Some(tree));
        self.count += 1;
        next_id
    }

    fn take(mut self, id: TreeId) -> (CowGroupWithRemoved<I, S>, RleTree<I, S, param::EnableCow>) {
        let tree = self.trees[id.0].take().unwrap();
        let with_removed = CowGroupWithRemoved { group: self, removed: id };
        (with_removed, tree)
    }
}

impl<I, S> CowGroupWithRemoved<I, S> {
    fn done(self, tree: RleTree<I, S, param::EnableCow>) -> CowGroup<I, S> {
        let mut group = self.group;
        let idx = self.removed.0;
        assert!(group.trees[idx].is_none());
        group.trees[idx] = Some(tree);
        group
    }

    fn discard(mut self) -> Option<CowGroup<I, S>> {
        match self.group.count {
            1 => None,
            _ => {
                self.group.count -= 1;
                Some(self.group)
            }
        }
    }
}

impl<I, S> Drop for CowGroup<I, S> {
    fn drop(&mut self) {
        // Drop trees in the reverse order of creation, to match the behavior that we'll get when
        // recreating the sequence of operations as a unit test, as the trees go out of scope.
        for t in self.trees.iter_mut().rev() {
            _ = t.take();
        }
    }
}

pub enum StableRefOperation<I, S> {
    /// A `BasicOperation` on the tree
    Basic(BasicOperation<I, S>),
    /// `let {ref_id} = tree.get({index}).stable_ref()`
    MakeRef {
        index: I,
        ref_id: Result<StableRefId, ()>,
    },
    /// Validate `{ref_id}.get(&tree)`
    CheckRef {
        ref_id: StableRefId,
        value: Option<(Range<I>, S)>,
    },
    /// `drop({0})`
    DiscardRef(StableRefId),
}

impl<I, S> ArbitraryOp for StableRefOperation<I, S>
where
    I: for<'d> Arbitrary<'d> + UnwindSafe + RefUnwindSafe + RustType + RustExpr + Index,
    S: for<'d> Arbitrary<'d>
        + UnwindSafe
        + RefUnwindSafe
        + RustType
        + RustExpr
        + Slice<I>
        + Debug
        + Clone
        + PartialEq,
{
    type FakeState = FakeStableRefGroup<I, S>;
    type Context = ();
    type RealState<'a> = StableRefGroup<I, S>;

    fn fake_state() -> Self::FakeState {
        FakeStableRefGroup::new()
    }

    fn context() -> Self::Context {}

    fn real_state(_ctx: &()) -> Self::RealState<'_> {
        StableRefGroup::new()
    }

    fn generate(
        u: &mut Unstructured<'_>,
        mut group: Self::FakeState,
    ) -> arbitrary::Result<(Self, Option<Self::FakeState>)> {
        let basic_count = std::mem::variant_count::<BasicOperation<I, S>>();
        let mut refs_count = std::mem::variant_count::<StableRefOperation<I, S>>() - 1;
        if group.is_empty() {
            refs_count -= 2; // skip CheckRef and DiscardRef, don't have any refs!
        }

        match u.int_in_range(0..=basic_count + refs_count + 1)? {
            // StableRefOperation::MakeRef
            0 => {
                let FakeStableRefGroup { mut fake, refs, num_refs } = group;

                let index = I::arbitrary(u)?;
                let result = expect_might_panic(move || {
                    let stable_ref = fake.make_ref(index);
                    (fake, stable_ref)
                });
                let (ref_id, new_state) = match result {
                    Ok((fake, stable_ref)) => {
                        group = FakeStableRefGroup { fake, refs, num_refs };
                        let id = group.add(stable_ref);
                        (Ok(id), Some(group))
                    }
                    Err(_) => (Err(()), None),
                };
                Ok((StableRefOperation::MakeRef { index, ref_id }, new_state))
            }
            // StableRefOperation::CheckRef
            1 if !group.is_empty() => {
                let ref_id = group.generate_id(u)?;
                let stable_ref = group.get(ref_id);
                let value =
                    group.fake.get_ref(stable_ref).map(|(range, slice)| (range, slice.clone()));
                Ok((StableRefOperation::CheckRef { ref_id, value }, Some(group)))
            }
            // StableRefOperation::DiscardRef
            2 if !group.is_empty() => {
                let ref_id = group.generate_id(u)?;
                _ = group.take(ref_id);
                Ok((StableRefOperation::DiscardRef(ref_id), Some(group)))
            }
            // StableRefOperation::Basic ...
            c if c >= refs_count => {
                let FakeStableRefGroup { fake, refs, num_refs } = group;
                let (basic, maybe_fake) = BasicOperation::generate(u, fake)?;
                let new_state = match maybe_fake {
                    Some((fake, _)) => Some(FakeStableRefGroup { fake, refs, num_refs }),
                    None => None,
                };
                Ok((StableRefOperation::Basic(basic), new_state))
            }
            v => unreachable!("bad StableRefOperation variant {v}"),
        }
    }

    fn execute_assert(
        &self,
        _ctx: &(),
        mut group: StableRefGroup<I, S>,
    ) -> Option<StableRefGroup<I, S>> {
        match self {
            StableRefOperation::Basic(op) => {
                let StableRefGroup { tree, refs, num_refs } = group;
                op.execute_assert(tree).map(|(tree, _)| StableRefGroup { tree, refs, num_refs })
            }
            &StableRefOperation::MakeRef { index, ref_id } => match ref_id {
                Ok(expected_id) => {
                    let stable_ref = group.tree.get(index).stable_ref();
                    let id = group.add(stable_ref);
                    assert_eq!(id, expected_id);
                    Some(group)
                }
                Err(()) => {
                    assert!(expect_might_panic(|| group.tree.get(index)).is_err());
                    None
                }
            },
            StableRefOperation::CheckRef { ref_id, value } => {
                let stable_ref = group.get(*ref_id);
                let actual = stable_ref.get(&group.tree).map(|e| (e.range(), e.slice()));
                let expected = value.as_ref().map(|(r, s)| (r.clone(), s));
                assert_eq!(expected, actual);
                Some(group)
            }
            &StableRefOperation::DiscardRef(ref_id) => {
                let stable_ref = group.take(ref_id);
                drop(stable_ref);
                Some(group)
            }
        }
    }

    fn write_init_stmts(f: &mut fmt::Formatter) -> fmt::Result {
        f.write_fmt(format_args!(
            "    let mut tree: RleTree<{I}, {S}, EnableRefs> = RleTree::new_empty();\n",
            I = I::display_rust_type(),
            S = S::display_rust_type(),
        ))
    }

    fn write_execute_stmts(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            StableRefOperation::Basic(op) => op.write_execute_stmts(
                f,
                BasicOperationFormatFlags { tree: &"tree", remove_into: None },
            ),
            StableRefOperation::MakeRef { index, ref_id } => match ref_id {
                Ok(ref_id) => f.write_fmt(format_args!(
                    "    let {ref_id} = tree.get({index}).stable_ref();\n",
                    index = index.display_rust_expr(),
                )),
                Err(()) => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(|| tree.get({index})).is_err());\n",
                    index = index.display_rust_expr(),
                )),
            },
            StableRefOperation::CheckRef { ref_id, value } => match value {
                None => f.write_fmt(format_args!("    assert!({ref_id}.get(&tree).is_none());\n")),
                Some((range, slice)) => {
                    f.write_str("    {\n")?;
                    f.write_fmt(format_args!(
                        "        let entry = {ref_id}.get(&tree).unwrap();\n"
                    ))?;
                    f.write_fmt(format_args!(
                        "        assert_eq!(entry.range(), {range});\n",
                        range = range.display_rust_expr(),
                    ))?;
                    f.write_fmt(format_args!(
                        "        assert_eq!(entry.slice(), {slice});\n",
                        slice = slice.display_rust_expr(),
                    ))?;
                    f.write_str("    }\n")
                }
            },
            StableRefOperation::DiscardRef(ref_id) => {
                f.write_fmt(format_args!("    drop({ref_id});\n"))
            }
        }
    }
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct StableRefId(usize);

impl Display for StableRefId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_fmt(format_args!("ref_{id}", id = self.0))
    }
}

pub struct FakeStableRefGroup<I, S> {
    fake: Fake<I, S>,
    refs: Vec<Option<FakeStableRef>>,
    num_refs: usize,
}

impl<I, S> FakeStableRefGroup<I, S>
where
    I: Index,
    S: Slice<I>,
{
    fn new() -> Self {
        FakeStableRefGroup {
            fake: Fake::new_empty(),
            refs: Vec::new(),
            num_refs: 0,
        }
    }

    fn is_empty(&self) -> bool {
        self.refs.is_empty()
    }

    fn generate_id(&self, u: &mut Unstructured<'_>) -> arbitrary::Result<StableRefId> {
        let mut idx = u.choose_index(self.num_refs)?;
        for (i, f) in self.refs.iter().enumerate() {
            if f.is_none() {
                idx += 1;
            }
            if idx == i {
                assert!(f.is_some());
                return Ok(StableRefId(idx));
            }
        }

        panic!("unexpectedly failed to generate StableRefId")
    }

    fn get(&self, id: StableRefId) -> &FakeStableRef {
        self.refs[id.0].as_ref().unwrap()
    }

    fn add(&mut self, fake_ref: FakeStableRef) -> StableRefId {
        let next_id = StableRefId(self.refs.len());
        self.refs.push(Some(fake_ref));
        self.num_refs += 1;
        next_id
    }

    fn take(&mut self, id: StableRefId) -> FakeStableRef {
        let r = self.refs[id.0].take().unwrap();
        self.num_refs -= 1;
        r
    }
}

pub struct StableRefGroup<I, S> {
    tree: RleTree<I, S, param::EnableRefs>,
    refs: Vec<Option<StableRef<I, S>>>,
    num_refs: usize,
}

impl<I, S> StableRefGroup<I, S>
where
    I: Index,
    S: Slice<I>,
{
    fn new() -> Self {
        StableRefGroup {
            tree: RleTree::new_empty(),
            refs: Vec::new(),
            num_refs: 0,
        }
    }

    fn get(&self, id: StableRefId) -> &StableRef<I, S> {
        self.refs[id.0].as_ref().unwrap()
    }

    fn add(&mut self, stable_ref: StableRef<I, S>) -> StableRefId {
        let next_id = StableRefId(self.refs.len());
        self.refs.push(Some(stable_ref));
        self.num_refs += 1;
        next_id
    }

    fn take(&mut self, id: StableRefId) -> StableRef<I, S> {
        let r = self.refs[id.0].take().unwrap();
        self.num_refs -= 1;
        r
    }
}
