use arbitrary::{Arbitrary, Unstructured};
use std::fmt::{self, Debug, Display};
use std::ops::{Bound, Range};
use std::panic::{self, RefUnwindSafe, UnwindSafe};

use crate::fuzz::{Fake, IndexInfo, RustExpr, RustType, TrackedIndex, TrackedSlice};
use crate::{Index, RleTree, Slice};

/// An operation on an [`RleTree`] (or group of `RleTree`s) that may be generated by a fuzzer
///
/// Usage proceeds in two phases:
///
/// 1. The initial generation of a sequence of operations (via [`OpSequence`]), using a faked
///    implementation to determine the correct results; and
/// 2. Run the operations against real `RleTree`s and check the results against the ones expected
///    from the faked implementation
///
/// If there are any differences from the expected results, the `Debug` implementation of
/// `OpSequence` uses `write_init_stmt()` and `write_stmt()` to print a unit test to reproduce the
/// failure.
pub trait ArbitraryOp: Sized {
    /// State used during generation, as a "ground truth" implementation
    type FakeState;
    /// Context for validation, that the state may borrow from
    type Context;
    /// State used during validation
    type RealState<'c>;

    /// Produces the initial `FakeState`
    fn fake_state() -> Self::FakeState;
    /// Produces the initial context for validation
    fn context() -> Self::Context;
    /// Produces the initial `RealState`
    fn real_state<'c>(ctx: &'c Self::Context) -> Self::RealState<'c>;

    /// Generates the operation from
    fn generate(
        u: &mut Unstructured<'_>,
        state: Self::FakeState,
    ) -> arbitrary::Result<(Self, Option<Self::FakeState>)>;

    /// Executes the operation on the state, and assert that it is
    fn execute_assert<'c>(
        &self,
        ctx: &'c Self::Context,
        state: Self::RealState<'c>,
    ) -> Option<Self::RealState<'c>>;

    /// Writes the start of a unit test to reproduce the assertions from these `ArbitraryOp`s
    fn write_test_start(f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("#[test]\n")?;
        f.write_str("fn test_case() {\n")?;
        Ok(())
    }

    /// Writes the statements at the start of a unit test to reproduce the initial `RealState`
    fn write_init_stmts(f: &mut fmt::Formatter) -> fmt::Result;

    /// Writes the statements to execute the operation and check its results
    fn write_execute_stmts(&self, f: &mut fmt::Formatter) -> fmt::Result;

    fn write_test_end(f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("}\n")?;
        Ok(())
    }
}

/// A sequence of [`ArbitraryOp`]s
pub struct OpSequence<C> {
    ops: Vec<C>,
}

impl<'d, Op> Arbitrary<'d> for OpSequence<Op>
where
    Op: ArbitraryOp,
{
    fn arbitrary(u: &mut Unstructured<'d>) -> arbitrary::Result<Self> {
        let mut ops: Vec<Op> = Vec::new();

        let mut state = Some(Op::fake_state());

        while let Some(s) = state
            && !u.is_empty()
        {
            let (op, next_state) = Op::generate(u, s)?;
            ops.push(op);
            state = next_state;
        }

        Ok(OpSequence { ops })
    }
}

impl<Op: ArbitraryOp> OpSequence<Op> {
    /// Executes the sequence of operations, checking at each step that the result matches what's
    /// expected from the faked state
    pub fn execute_assert(&self) {
        let ctx = Op::context();
        let mut state = Op::real_state(&ctx);
        let mut ops = self.ops.iter().enumerate().peekable();
        while let Some((idx, op)) = ops.next() {
            let next_state = op.execute_assert(&ctx, state);
            match next_state {
                Some(s) => state = s,
                // Operation consumed state & didn't give it back.
                // Ok if this is the last op, otherwise unexpected.
                None => match ops.peek() {
                    None => return,
                    Some(_) => panic!(
                        "bad ArbitraryOp impl? op idx={idx} executed without returning state"
                    ),
                },
            }
        }
    }
}

impl<Op> Debug for OpSequence<Op>
where
    Op: ArbitraryOp,
{
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        Op::write_test_start(f)?;
        Op::write_init_stmts(f)?;
        for c in &self.ops {
            c.write_execute_stmts(f)?;
        }
        Op::write_test_end(f)?;
        Ok(())
    }
}

fn expect_might_panic<R, F: UnwindSafe + FnOnce() -> R>(f: F) -> Result<R, ()> {
    // set a custom hook that does nothing, so we don't print panic information every time the mock
    // implementation panics
    panic::set_hook(Box::new(|_| {}));

    let result = panic::catch_unwind(f).map_err(|_| ());

    // remove our custom hook
    let _ = panic::take_hook();

    result
}

#[derive(Clone)]
pub enum BasicOperation<I, S> {
    /// `tree.get(index)`
    Get {
        index: I,
        /// If the call to `get()` should panic, then `Err(())`; otherwise, the range and slice
        /// returned by `get()`.
        expected: Result<(Range<I>, S), ()>,
    },
    /// `tree.iter((start, end))`
    Iter {
        start: Bound<I>,
        end: Bound<I>,
        /// If the call to `iter()` should panic, then `Err(())`; otherwise, the sequence of
        /// operations on the iterator, and their expected results.
        access: Result<Vec<IterOperation<I, S>>, ()>,
    },
    /// `tree.into_iter()`
    IntoIter {
        /// The sequence of operations on the iterator, and their expected results.
        access: Vec<IterOperation<I, S>>,
    },
    /// `tree.insert(index, slice, size)`
    Insert {
        index: I,
        slice: S,
        size: I,
        /// Is this insertion expected to panic?
        panics: bool,
    },
    /// `tree.replace((start, end), slice)`
    ///
    /// We intentionally don't do anything with the returned values.
    Replace {
        start: Bound<I>,
        end: Bound<I>,
        slice: S,
        /// Helper information: `tree.size()` before this operation
        tree_size: I,
        /// Is this removal expected to panic?
        panics: bool,
    },
    /// `_ = tree.remove((start, end))`
    ///
    /// While this does return a new `RleTree`, we intentionally don't do anything with it.
    /// We get decent coverage from `Drain` already, and it's better to keep the state simple here.
    Remove {
        start: Bound<I>,
        end: Bound<I>,
        /// Helper information: `tree.size()` before this operation
        tree_size: I,
        /// Is this removal expected to panic?
        panics: bool,
    },
    /// `tree.drain((start, end))`
    Drain {
        start: Bound<I>,
        end: Bound<I>,
        /// Helper information: `tree.size()` before this operation
        tree_size: I,
        /// If the call to `drain()` should panic, then `Err(())`; otherwise, the sequence of
        /// operations on the iterator, and their expected results.
        access: Result<Vec<IterOperation<I, S>>, ()>,
    },
    /// `tree.validate_balance()`
    Validate,
}

#[derive(Clone)]
pub struct IterOperation<I, S> {
    direction: IterDirection,
    value: Option<(Range<I>, S)>,
}

#[derive(Copy, Clone, Arbitrary)]
enum IterDirection {
    Front,
    Back,
}

fn format_bounds<'b, I: RustExpr>(start: &'b Bound<I>, end: &'b Bound<I>) -> impl 'b + Display {
    struct R<'b, I>(&'b Bound<I>, &'b Bound<I>);
    impl<'b, I: RustExpr> Display for R<'b, I> {
        fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
            match (self.0, self.1) {
                (Bound::Unbounded, Bound::Unbounded) => f.write_str(".."),
                (Bound::Unbounded, Bound::Excluded(e)) => {
                    f.write_fmt(format_args!("..{}", e.display_rust_expr()))
                }
                (Bound::Unbounded, Bound::Included(e)) => {
                    f.write_fmt(format_args!("..={}", e.display_rust_expr()))
                }
                (Bound::Excluded(_), _) => unreachable!(),
                (Bound::Included(s), Bound::Unbounded) => {
                    f.write_fmt(format_args!("{}..", s.display_rust_expr()))
                }
                (Bound::Included(s), Bound::Excluded(e)) => f.write_fmt(format_args!(
                    "{}..{}",
                    s.display_rust_expr(),
                    e.display_rust_expr()
                )),
                (Bound::Included(s), Bound::Included(e)) => f.write_fmt(format_args!(
                    "{}..={}",
                    s.display_rust_expr(),
                    e.display_rust_expr()
                )),
            }
        }
    }

    R(start, end)
}

impl<I, S> ArbitraryOp for BasicOperation<I, S>
where
    I: for<'d> Arbitrary<'d> + UnwindSafe + RefUnwindSafe + RustType + RustExpr + Index,
    S: for<'d> Arbitrary<'d>
        + UnwindSafe
        + RefUnwindSafe
        + RustType
        + RustExpr
        + Slice<I>
        + Debug
        + Clone
        + PartialEq,
{
    type FakeState = Fake<I, S>;
    type Context = ();
    type RealState<'a> = RleTree<I, S>;

    fn fake_state() -> Self::FakeState {
        Fake::new_empty()
    }

    fn context() -> Self::Context {}

    fn real_state(_ctx: &()) -> Self::RealState<'_> {
        RleTree::new_empty()
    }

    fn generate(
        u: &mut Unstructured<'_>,
        mut fake: Fake<I, S>,
    ) -> arbitrary::Result<(Self, Option<Fake<I, S>>)> {
        match u.int_in_range(0..=7)? {
            // BasicOperation::Get
            0 => {
                let index = I::arbitrary(u)?;
                let result = expect_might_panic(move || {
                    let (range, slice) = fake.get(index);
                    (range, S::clone(slice), fake)
                });
                let (expected, new_state) = match result {
                    Ok((range, slice, fake)) => (Ok((range, slice)), Some(fake)),
                    Err(_) => (Err(()), None),
                };

                Ok((BasicOperation::Get { index, expected }, new_state))
            }
            // BasicOperation::Iter
            1 => {
                let start = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded,
                    1 => Bound::Included(I::arbitrary(u)?),
                    _ => unreachable!(),
                };
                let end = match u.int_in_range(0..=2)? {
                    0 => Bound::Unbounded,
                    1 => Bound::Included(I::arbitrary(u)?),
                    2 => Bound::Excluded(I::arbitrary(u)?),
                    _ => unreachable!(),
                };

                let access_directions = u.arbitrary::<Vec<IterDirection>>()?;
                let result = expect_might_panic(move || {
                    let mut iter = fake.iter((start, end));
                    let mut access = Vec::new();
                    for direction in access_directions {
                        let v = match direction {
                            IterDirection::Front => iter.next(),
                            IterDirection::Back => iter.next_back(),
                        };

                        access.push(IterOperation {
                            direction,
                            value: v.map(|(r, s)| (r, s.clone())),
                        });
                    }
                    (access, fake)
                });

                let (access, new_state) = match result {
                    Ok((vals, fake)) => (Ok(vals), Some(fake)),
                    Err(_) => (Err(()), None),
                };

                Ok((BasicOperation::Iter { start, end, access }, new_state))
            }
            // BasicOperation::IntoIter
            2 => {
                let access_directions = u.arbitrary::<Vec<IterDirection>>()?;
                let mut iter = fake.into_iter();
                let mut access = Vec::new();
                for direction in access_directions {
                    let value = match direction {
                        IterDirection::Front => iter.next(),
                        IterDirection::Back => iter.next_back(),
                    };

                    access.push(IterOperation { direction, value });
                }
                Ok((BasicOperation::IntoIter { access }, None))
            }
            // BasicOperation::Insert
            3 => {
                let index = I::arbitrary(u)?;
                let slice = S::arbitrary(u)?;
                let size = I::arbitrary(u)?;
                let slice_cloned = slice.clone();
                let result = expect_might_panic(move || {
                    fake.insert(index, slice_cloned, size);
                    fake
                });
                let (panics, new_state) = match result {
                    Ok(fake) => (false, Some(fake)),
                    Err(_) => (true, None),
                };

                Ok((BasicOperation::Insert { index, slice, size, panics }, new_state))
            }
            // BasicOperation::Replace
            4 => {
                let start = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded,
                    1 => Bound::Included(I::arbitrary(u)?),
                    _ => unreachable!(),
                };
                let end = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded,
                    1 => Bound::Excluded(I::arbitrary(u)?),
                    _ => unreachable!(),
                };
                let tree_size = fake.size();

                let slice = S::arbitrary(u)?;

                let slice_cloned = slice.clone();
                let result = expect_might_panic(move || {
                    _ = fake.replace((start, end), slice_cloned);
                    fake
                });

                let (panics, new_state) = match result {
                    Ok(fake) => (false, Some(fake)),
                    Err(_) => (true, None),
                };

                Ok((BasicOperation::Replace { start, end, slice, tree_size, panics }, new_state))
            }
            // BasicOperation::Remove
            5 => {
                let start = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded,
                    1 => Bound::Included(I::arbitrary(u)?),
                    _ => unreachable!(),
                };
                let end = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded,
                    1 => Bound::Excluded(I::arbitrary(u)?),
                    _ => unreachable!(),
                };
                let tree_size = fake.size();

                let result = expect_might_panic(move || {
                    fake.remove((start, end));
                    fake
                });

                let (panics, new_state) = match result {
                    Ok(fake) => (false, Some(fake)),
                    Err(_) => (true, None),
                };

                Ok((BasicOperation::Remove { start, end, tree_size, panics }, new_state))
            }
            // BasicOperation::Drain
            6 => {
                let start = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded,
                    1 => Bound::Included(I::arbitrary(u)?),
                    _ => unreachable!(),
                };
                let end = match u.int_in_range(0..=1)? {
                    0 => Bound::Unbounded,
                    1 => Bound::Excluded(I::arbitrary(u)?),
                    _ => unreachable!(),
                };
                let tree_size = fake.size();

                let access_directions = u.arbitrary::<Vec<IterDirection>>()?;
                let result = expect_might_panic(move || {
                    let mut drain = fake.drain((start, end));
                    let mut access = Vec::new();
                    for direction in access_directions {
                        let value = match direction {
                            IterDirection::Front => drain.next(),
                            IterDirection::Back => drain.next_back(),
                        };
                        access.push(IterOperation { direction, value });
                    }
                    drop(drain);
                    (access, fake)
                });

                let (access, new_state) = match result {
                    Ok((vals, fake)) => (Ok(vals), Some(fake)),
                    Err(_) => (Err(()), None),
                };

                Ok((BasicOperation::Drain { start, end, tree_size, access }, new_state))
            }
            // BasicOperation::Validate
            7 => Ok((BasicOperation::Validate, Some(fake))),
            v => unreachable!("bad BasicOperation variant {v}"),
        }
    }

    fn execute_assert(&self, _ctx: &(), tree: Self::RealState<'_>) -> Option<Self::RealState<'_>> {
        BasicOperation::execute_assert(self, tree)
    }

    fn write_init_stmts(f: &mut fmt::Formatter) -> fmt::Result {
        f.write_fmt(format_args!(
            "    let mut tree: RleTree<{I}, {S}> = RleTree::new_empty();\n",
            I = I::display_rust_type(),
            S = S::display_rust_type(),
        ))
    }

    fn write_execute_stmts(&self, f: &mut fmt::Formatter) -> fmt::Result {
        BasicOperation::write_execute_stmts(
            self,
            f,
            BasicOperationFormatFlags { tree: &"tree", remove_into: None },
        )
    }
}

struct BasicOperationFormatFlags<'d> {
    tree: &'d dyn fmt::Display,
    remove_into: Option<&'d dyn fmt::Display>,
}

impl<I, S> BasicOperation<I, S> {
    fn execute_assert(&self, mut tree: RleTree<I, S>) -> Option<RleTree<I, S>>
    where
        I: UnwindSafe + RefUnwindSafe + Index,
        S: UnwindSafe + RefUnwindSafe + Slice<I> + Debug + PartialEq + Clone,
    {
        match self {
            &BasicOperation::Get { index, ref expected } => match expected {
                Ok((range, slice)) => {
                    let entry = tree.get(index);
                    assert_eq!(entry.range(), *range);
                    assert_eq!(entry.slice(), slice);
                    drop(entry);
                    Some(tree)
                }
                Err(()) => {
                    assert!(expect_might_panic(|| tree.get(index)).is_err());
                    None
                }
            },
            &BasicOperation::Iter { start, end, ref access } => match access {
                Ok(seq) => {
                    let mut iter = tree.iter((start, end));
                    for op in seq {
                        let item = match op.direction {
                            IterDirection::Front => iter.next(),
                            IterDirection::Back => iter.next_back(),
                        };

                        let actual = item.map(|entry| (entry.range(), entry.slice().clone()));
                        assert_eq!(actual, op.value);
                    }
                    drop(iter);
                    Some(tree)
                }
                Err(()) => {
                    assert!(expect_might_panic(|| tree.iter((start, end))).is_err());
                    None
                }
            },
            BasicOperation::IntoIter { access } => {
                let mut iter = tree.into_iter();
                for op in access {
                    let item = match op.direction {
                        IterDirection::Front => iter.next(),
                        IterDirection::Back => iter.next_back(),
                    };

                    assert_eq!(item, op.value);
                }
                None
            }
            BasicOperation::Insert { index, slice, size, panics } => match panics {
                false => {
                    tree.insert(*index, slice.clone(), *size);
                    Some(tree)
                }
                true => {
                    let slice_clone = slice.clone();
                    assert!(
                        expect_might_panic(move || tree.insert(*index, slice_clone, *size))
                            .is_err()
                    );
                    None
                }
            },
            BasicOperation::Replace { start, end, slice, panics, .. } => match panics {
                false => {
                    _ = tree.replace((*start, *end), slice.clone());
                    Some(tree)
                }
                true => {
                    let slice_clone = slice.clone();
                    assert!(
                        expect_might_panic(move || tree.replace((*start, *end), slice_clone))
                            .is_err()
                    );
                    None
                }
            },
            BasicOperation::Remove { start, end, panics, .. } => match panics {
                false => {
                    tree.remove((*start, *end));
                    Some(tree)
                }
                true => {
                    assert!(expect_might_panic(move || tree.remove((*start, *end))).is_err());
                    None
                }
            },
            BasicOperation::Drain { start, end, access, .. } => match access {
                Ok(seq) => {
                    let mut drain = tree.drain((*start, *end));
                    for op in seq {
                        let item = match op.direction {
                            IterDirection::Front => drain.next(),
                            IterDirection::Back => drain.next_back(),
                        };

                        assert_eq!(item, op.value);
                    }
                    drop(drain);
                    Some(tree)
                }
                Err(()) => {
                    assert!(
                        expect_might_panic(move || {
                            _ = tree.drain((*start, *end));
                        })
                        .is_err()
                    );
                    None
                }
            },
            BasicOperation::Validate => {
                tree.validate_balance();
                Some(tree)
            }
        }
    }

    fn write_execute_stmts(
        &self,
        f: &mut fmt::Formatter,
        flags: BasicOperationFormatFlags<'_>,
    ) -> fmt::Result
    where
        I: RustExpr,
        S: RustExpr,
    {
        let BasicOperationFormatFlags { tree, remove_into } = flags;

        match self {
            BasicOperation::Get { index, expected } => match expected {
                Ok((range, slice)) => {
                    f.write_str("    {\n")?;
                    f.write_fmt(format_args!(
                        "        let entry = {tree}.get({index});\n",
                        index = index.display_rust_expr()
                    ))?;
                    f.write_fmt(format_args!(
                        "        assert_eq!(entry.range(), {range});\n",
                        range = range.display_rust_expr()
                    ))?;
                    f.write_fmt(format_args!(
                        "        assert_eq!(entry.slice(), &{slice});\n",
                        slice = slice.display_rust_expr()
                    ))?;
                    f.write_str("    }\n")?;
                    Ok(())
                }
                Err(()) => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(|| {tree}.get({index})).is_err());\n",
                    index = index.display_rust_expr(),
                )),
            },
            BasicOperation::Iter { start, end, access } => match access {
                Ok(seq) if seq.is_empty() => f.write_fmt(format_args!(
                    "    let _ = {tree}.iter({range});\n",
                    range = format_bounds(start, end),
                )),
                Ok(seq) => {
                    // Sample output:
                    //
                    //   {
                    //       let mut iter = tree.iter({range});
                    //       {
                    //           let item = iter.{method}().unwrap();
                    //           assert_eq!(item.range(), {expected_range});
                    //           assert_eq!(item.slice(), {expected_slice});
                    //       }
                    //       assert!(iter.{method}().is_none());
                    //   }
                    f.write_str("    {\n")?;
                    f.write_fmt(format_args!(
                        "        let mut iter = {tree}.iter({range});\n",
                        range = format_bounds(start, end),
                    ))?;
                    for op in seq {
                        let method = match op.direction {
                            IterDirection::Front => "next",
                            IterDirection::Back => "next_back",
                        };

                        match &op.value {
                            None => f.write_fmt(format_args!("        assert!(iter.{method}().is_none());\n"))?,
                            Some((range, slice)) => {
                                f.write_str("        {\n")?;
                                f.write_fmt(format_args!("            let item = iter.{method}().unwrap();\n"))?;
                                f.write_fmt(format_args!("            assert_eq!(item.range(), {});\n", range.display_rust_expr()))?;
                                f.write_fmt(format_args!("            assert_eq!(item.slice(), &{});\n", slice.display_rust_expr()))?;
                                f.write_str("        }\n")?;
                            },
                        }
                    }
                    f.write_str("    }\n")
                },
                Err(()) => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(|| {tree}.iter({range})).is_err());\n",
                    range = format_bounds(start, end),
                )),
            },
            BasicOperation::IntoIter { access } => {
                if access.is_empty() {
                    f.write_fmt(format_args!("    let _ = {tree}.into_iter();\n"))
                } else {
                    // Sample output:
                    //
                    //   {
                    //       let mut iter = tree.into_iter();
                    //       assert_eq!(iter.{method}(), Some(({expected_range}, {expected_slice})));
                    //       assert_eq!(iter.{method}(), None);
                    //   }
                    f.write_str("    {\n")?;
                    f.write_fmt(format_args!("        let mut iter = {tree}.into_iter();\n"))?;
                    for op in access {
                        let method = match op.direction {
                            IterDirection::Front => "next",
                            IterDirection::Back => "next_back",
                        };

                        f.write_fmt(format_args!(
                            "        assert_eq!(iter.{method}(), {expected});\n",
                            expected = op.value.display_rust_expr(),
                        ))?;
                    }
                    f.write_str("    }\n")
                }
            }
            BasicOperation::Insert { index, slice, size, panics } => match panics {
                false => f.write_fmt(format_args!(
                    "    {tree}.insert({index}, {slice}, {size});\n",
                    index = index.display_rust_expr(),
                    slice = slice.display_rust_expr(),
                    size = size.display_rust_expr(),
                )),
                true => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(move || {tree}.insert({index}, {slice}, {size})).is_err());\n",
                    index = index.display_rust_expr(),
                    slice = slice.display_rust_expr(),
                    size = size.display_rust_expr(),
                )),
            },
            BasicOperation::Replace { start, end, slice, panics, .. } => match panics {
                false => f.write_fmt(format_args!(
                    "    _ = {tree}.replace({range}, {slice});\n",
                    range = format_bounds(start, end),
                    slice = slice.display_rust_expr(),
                )),
                true => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(move || {tree}.replace({range}, {slice})).is_err());\n",
                    range = format_bounds(start, end),
                    slice = slice.display_rust_expr(),
                )),
            },
            BasicOperation::Remove { start, end, panics, .. } => match panics {
                false => f.write_fmt(format_args!(
                    "    {lhs} = {tree}.remove({range});\n",
                    lhs = remove_into.unwrap_or(&"_"),
                    range = format_bounds(start, end),
                )),
                true => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(move || {tree}.remove({range})).is_err());\n",
                    range = format_bounds(start, end),
                )),
            },
            BasicOperation::Drain { start, end, access, .. } => match access {
                Ok(seq) if seq.is_empty() => f.write_fmt(format_args!(
                    "    let _ = {tree}.drain({range});\n",
                    range = format_bounds(start, end),
                )),
                Ok(seq) => {
                    // Sample output:
                    //
                    //   {
                    //       let mut drain = tree.drain({range});
                    //       assert_eq!(drain.{method}(), Some(({expected_range}, {expected_slice})));
                    //       assert_eq!(drain.{method}(), None);
                    //   }
                    f.write_str("    {\n")?;
                    f.write_fmt(format_args!(
                        "        let mut drain = {tree}.drain({range});\n",
                        range = format_bounds(start, end),
                    ))?;
                    for op in seq {
                        let method = match op.direction {
                            IterDirection::Front => "next",
                            IterDirection::Back => "next_back",
                        };

                        f.write_fmt(format_args!(
                            "        assert_eq!(drain.{method}(), {expected});\n",
                            expected = op.value.display_rust_expr(),
                        ))?;
                    }
                    f.write_str("    }\n")
                },
                Err(()) => f.write_fmt(format_args!(
                    "    assert!(std::panic::catch_unwind(move || drop({tree}.drain({range}))).is_err());\n",
                    range = format_bounds(start, end),
                )),
            },
            BasicOperation::Validate => f.write_fmt(format_args!(
                "    {tree}.validate_balance();\n",
            )),
        }
    }
}

/// Like [`BasicOperation`], but checks that [`RleTree`] respects index usage invariants
pub struct CheckedIndexOperation<I, S>(BasicOperation<I, S>);

impl<I, S> ArbitraryOp for CheckedIndexOperation<I, S>
where
    I: 'static + for<'d> Arbitrary<'d> + UnwindSafe + RefUnwindSafe + RustType + RustExpr + Index,
    S: 'static
        + for<'d> Arbitrary<'d>
        + UnwindSafe
        + RefUnwindSafe
        + RustType
        + RustExpr
        + Slice<I>
        + Debug
        + Clone
        + PartialEq,
{
    type FakeState = Fake<I, S>;
    type Context = IndexInfo<I>;
    type RealState<'c> = RleTree<TrackedIndex<'c, I>, TrackedSlice<S>>;

    fn fake_state() -> Self::FakeState {
        Fake::new_empty()
    }

    fn context() -> Self::Context {
        IndexInfo::new()
    }

    fn real_state<'c>(_ctx: &'c IndexInfo<I>) -> RleTree<TrackedIndex<'c, I>, TrackedSlice<S>> {
        RleTree::new_empty()
    }

    fn generate(
        u: &mut Unstructured<'_>,
        fake: Fake<I, S>,
    ) -> arbitrary::Result<(Self, Option<Fake<I, S>>)> {
        match BasicOperation::generate(u, fake) {
            Err(e) => Err(e),
            Ok((this, next_state)) => Ok((CheckedIndexOperation(this), next_state)),
        }
    }

    fn execute_assert<'c>(
        &self,
        info: &'c IndexInfo<I>,
        tree: RleTree<TrackedIndex<'c, I>, TrackedSlice<S>>,
    ) -> Option<RleTree<TrackedIndex<'c, I>, TrackedSlice<S>>> {
        // Convert from: BasicOperation<I, S> to BasicOperation<TrackedIndex<I>, TrackedSlice<S>>,
        // matching the RleTree.
        let map_bound = |bound| match bound {
            Bound::Unbounded => Bound::Unbounded,
            Bound::Included(idx) => Bound::Included(info.i(idx)),
            Bound::Excluded(idx) => Bound::Excluded(info.i(idx)),
        };
        let map_range = |range: Range<_>| info.i(range.start)..info.i(range.end);
        let map_iter_seq = |seq: Vec<IterOperation<_, _>>| {
            seq.into_iter()
                .map(|op| IterOperation {
                    direction: op.direction,
                    value: op.value.map(|(r, s)| (map_range(r), TrackedSlice(s))),
                })
                .collect::<Vec<_>>()
        };
        let bound_value = |bound, default| match bound {
            Bound::Unbounded => default,
            Bound::Included(idx) | Bound::Excluded(idx) => idx,
        };

        let tracked = match self.0.clone() {
            BasicOperation::Get { index, expected } => BasicOperation::Get {
                index: info.i(index),
                expected: expected.map(|(r, s)| (map_range(r), TrackedSlice(s))),
            },
            BasicOperation::Iter { start, end, access } => BasicOperation::Iter {
                start: map_bound(start),
                end: map_bound(end),
                access: access.map(map_iter_seq),
            },
            BasicOperation::IntoIter { access } => {
                BasicOperation::IntoIter { access: map_iter_seq(access) }
            }
            BasicOperation::Insert { index, slice, size, panics } => {
                let (index, size) = info.prepare_insert(index, size);
                BasicOperation::Insert { index, slice: TrackedSlice(slice), size, panics }
            }
            BasicOperation::Replace { start, end, slice, tree_size, panics } => {
                let start = map_bound(start);
                let end = map_bound(end);
                let slice = TrackedSlice(slice);
                let tree_size = info.i(tree_size);
                BasicOperation::Replace { start, end, slice, tree_size, panics }
            }
            BasicOperation::Remove { start, end, tree_size, panics } => {
                let range_start = bound_value(start, I::ZERO);
                let range_end = bound_value(end, tree.size().value());
                let start = map_bound(start);
                let end = map_bound(end);
                let tree_size = info.i(tree_size);
                info.prepare_remove(range_start, range_end);
                BasicOperation::Remove { start, end, panics, tree_size }
            }
            BasicOperation::Drain { start, end, tree_size, access } => {
                let range_start = bound_value(start, I::ZERO);
                let range_end = bound_value(end, tree.size().value());
                let start = map_bound(start);
                let end = map_bound(end);
                let tree_size = info.i(tree_size);
                let access = access.map(map_iter_seq);
                info.prepare_remove(range_start, range_end);
                BasicOperation::Drain { start, end, tree_size, access }
            }
            BasicOperation::Validate => BasicOperation::Validate,
        };

        BasicOperation::execute_assert(&tracked, tree)
    }

    fn write_init_stmts(f: &mut fmt::Formatter) -> fmt::Result {
        f.write_fmt(format_args!(
            "    let t: IndexInfo<{I}> = IndexInfo::new();\n",
            I = I::display_rust_type(),
        ))?;
        f.write_fmt(format_args!(
            "    let mut tree: RleTree<TrackedIndex<{I}>, TrackedSlice<{S}>> = RleTree::new_empty();\n",
            I = I::display_rust_type(),
            S = S::display_rust_type(),
        ))
    }

    fn write_execute_stmts(&self, f: &mut fmt::Formatter) -> fmt::Result {
        // Convert from: BasicOperation<I, S> to BasicOperation<CheckedIndex<I>, CheckedSlice<S>>,
        // which is slightly different from the RleTree, so that we can name external variables for
        // things like insertions & removals.
        let map_range =
            |range: Range<_>| CheckedIndex::Current(range.start)..CheckedIndex::Current(range.end);
        let map_bound = |bound| match bound {
            Bound::Unbounded => Bound::Unbounded,
            Bound::Included(idx) => Bound::Included(CheckedIndex::Current(idx)),
            Bound::Excluded(idx) => Bound::Excluded(CheckedIndex::Current(idx)),
        };
        let map_iter_seq = |seq: Vec<IterOperation<_, _>>| {
            seq.into_iter()
                .map(|op| IterOperation {
                    direction: op.direction,
                    value: op.value.map(|(r, s)| (map_range(r), CheckedSlice(s))),
                })
                .collect::<Vec<_>>()
        };

        let checked = match self.0.clone() {
            BasicOperation::Get { index, expected } => BasicOperation::Get {
                index: CheckedIndex::Current(index),
                expected: expected.map(|(r, s)| (map_range(r), CheckedSlice(s))),
            },
            BasicOperation::Iter { start, end, access } => BasicOperation::Iter {
                start: map_bound(start),
                end: map_bound(end),
                access: access.map(map_iter_seq),
            },
            BasicOperation::IntoIter { access } => {
                BasicOperation::IntoIter { access: map_iter_seq(access) }
            }
            BasicOperation::Insert { index, slice, size, panics } => {
                f.write_fmt(format_args!(
                    "    let (idx, size) = t.prepare_insert({index}, {size});\n",
                    index = index.display_rust_expr(),
                    size = size.display_rust_expr(),
                ))?;

                BasicOperation::Insert {
                    index: CheckedIndex::Named("idx"),
                    slice: CheckedSlice(slice),
                    size: CheckedIndex::Named("size"),
                    panics,
                }
            }
            BasicOperation::Replace { start, end, slice, tree_size, panics } => {
                BasicOperation::Replace {
                    start: map_bound(start),
                    end: map_bound(end),
                    slice: CheckedSlice(slice),
                    tree_size: CheckedIndex::Current(tree_size),
                    panics,
                }
            }
            BasicOperation::Remove { start, end, panics, tree_size } => {
                let (start, start_var, start_idx) = match start {
                    Bound::Unbounded => (Bound::Unbounded, "_", I::ZERO),
                    Bound::Included(idx) => {
                        (Bound::Included(CheckedIndex::Named("start")), "start", idx)
                    }
                    Bound::Excluded(idx) => {
                        (Bound::Excluded(CheckedIndex::Named("start")), "start", idx)
                    }
                };
                let (end, end_var, end_idx) = match end {
                    Bound::Unbounded => (Bound::Unbounded, "_", tree_size),
                    Bound::Included(idx) => {
                        (Bound::Included(CheckedIndex::Named("end")), "end", idx)
                    }
                    Bound::Excluded(idx) => {
                        (Bound::Excluded(CheckedIndex::Named("end")), "end", idx)
                    }
                };

                f.write_fmt(format_args!(
                    "    let ({start_var}, {end_var}) = t.prepare_remove({start_idx}, {end_idx});\n",
                    start_idx = start_idx.display_rust_expr(),
                    end_idx = end_idx.display_rust_expr(),
                ))?;
                let tree_size = CheckedIndex::Previous(tree_size);
                BasicOperation::Remove { start, end, tree_size, panics }
            }
            BasicOperation::Drain { start, end, tree_size, access } => {
                let (start, start_var, start_idx) = match start {
                    Bound::Unbounded => (Bound::Unbounded, "_", I::ZERO),
                    Bound::Included(idx) => {
                        (Bound::Included(CheckedIndex::Named("start")), "start", idx)
                    }
                    Bound::Excluded(idx) => {
                        (Bound::Excluded(CheckedIndex::Named("start")), "start", idx)
                    }
                };
                let (end, end_var, end_idx) = match end {
                    Bound::Unbounded => (Bound::Unbounded, "_", tree_size),
                    Bound::Included(idx) => {
                        (Bound::Included(CheckedIndex::Named("end")), "end", idx)
                    }
                    Bound::Excluded(idx) => {
                        (Bound::Excluded(CheckedIndex::Named("end")), "end", idx)
                    }
                };

                f.write_fmt(format_args!(
                    "    let ({start_var}, {end_var}) = t.prepare_remove({start_idx}, {end_idx});\n",
                    start_idx = start_idx.display_rust_expr(),
                    end_idx = end_idx.display_rust_expr(),
                ))?;

                let tree_size = CheckedIndex::Previous(tree_size);

                let access = access.map(|seq| {
                    seq.into_iter()
                        .map(|op| IterOperation {
                            direction: op.direction,
                            value: op.value.map(|(r, s)| {
                                let r =
                                    CheckedIndex::Previous(r.start)..CheckedIndex::Previous(r.end);
                                let s = CheckedSlice(s);
                                (r, s)
                            }),
                        })
                        .collect::<Vec<_>>()
                });

                BasicOperation::Drain { start, end, tree_size, access }
            }
            BasicOperation::Validate => BasicOperation::Validate,
        };

        BasicOperation::write_execute_stmts(
            &checked,
            f,
            BasicOperationFormatFlags { tree: &"tree", remove_into: None },
        )
    }
}

enum CheckedIndex<I> {
    Named(&'static str),
    Current(I),
    Previous(I),
}

impl<I: RustExpr> RustExpr for CheckedIndex<I> {
    fn write_rust_expr(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            CheckedIndex::Named(var) => f.write_str(var),
            CheckedIndex::Current(idx) => {
                f.write_fmt(format_args!("t.i({})", idx.display_rust_expr()))
            }
            CheckedIndex::Previous(idx) => {
                f.write_fmt(format_args!("t.p({})", idx.display_rust_expr()))
            }
        }
    }
}

struct CheckedSlice<S>(S);

impl<S: RustExpr> RustExpr for CheckedSlice<S> {
    fn write_rust_expr(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_fmt(format_args!("TrackedSlice({})", self.0.display_rust_expr()))
    }
}
